services:
  todo-api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ..:/app
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge