version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      - .:/app
    # Hot reload para desenvolvimento
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge